---
# These tasks are only for debugging purpose
#
# verbosity:  A number that controls when the debug is run,
#             if you set to 3 it will only run debug when -vvv or above

- name: DEBUG - whoami
  shell: whoami
  register: whoami
- debug: var=whoami.stdout verbosity=1

- name: DEBUG - pwd
  shell: pwd
  register: pwd
- debug: var=pwd.stdout verbosity=1

- name: DEBUG - uptime
  shell: uptime
  register: uptime
- debug: var=uptime.stdout verbosity=1

- name: Display all variables/facts known for a host
  debug:
    var: hostvars[inventory_hostname]
    verbosity: 4
