---

# To install all the roles defined in this file run:
#   ansible-galaxy install -r requirements.yml

# Roles from the Ansible Galaxy and GitHub

- src: schuerg.prerequisites

- src: https://github.com/geerlingguy/ansible-role-docker
  version: master
  name: geerlingguy.docker
